javascript:
var button = document.createElement("BUTTON");
var button2 = document.createElement("BUTTON");
var button3 = document.createElement("BUTTON");
var button4 = document.createElement("BUTTON");
button.style.position = "fixed";
button.style.width = "10%";
button.style.height = "15%";
button.style.backgroundColor = "white";
button.style.border = "2px solid black";
button.style.top = "85%";
button.style.left = "90%";
button.style.zIndex = "100";
button.style.fontSize = "1.8vw";
button.innerHTML = "Give Cookies";
button.addEventListener('click', function() {
var amount = prompt("how many cookies do you want");
amount = parseInt(amount);
Game.cookies = amount;
}, false);
button2.style.position = "fixed";
button2.style.width = "10%";
button2.style.height = "15%";
button2.style.backgroundColor = "white";
button2.style.border = "2px solid black";
button2.style.top = "40%";
button2.style.left = "90%";
button2.style.zIndex = "100";
button2.style.fontSize = "1.8vw";
button2.innerHTML = "Turn Off";
button2.addEventListener('click', function() {
    button.remove();
    button2.remove();
    button3.remove();
    button4.remove();
}, false);
button3.style.position = "fixed";
button3.style.width = "10%";
button3.style.height = "15%";
button3.style.backgroundColor = "white";
button3.style.border = "2px solid black";
button3.style.top = "70%";
button3.style.left = "90%";
button3.style.zIndex = "100";
button3.style.fontSize = "1.8vw";
button3.innerHTML = "Change cps";
button3.addEventListener('click', function() {
 var amount2 = prompt("What CPS do you want?");
amount = parseInt(amount2);
Game.cookiesPs = amount2;
}, false);
button4.style.position = "fixed";
button4.style.width = "10%";
button4.style.height = "15%";
button4.style.backgroundColor = "white";
button4.style.border = "2px solid black";
button4.style.top = "55%";
button4.style.left = "90%";
button4.style.zIndex = "100";
button4.style.fontSize = "1.8vw";
button4.innerHTML = "Ruin The Fun";
button4.addEventListener('click', function() {
Game.RuinTheFun;
}, false);
document.body.appendChild(button);
document.body.appendChild(button2);
document.body.appendChild(button3);
document.body.appendChild(button4);
